language: ruby
rvm:
  - 2.2.3
services:
  - mongodb
before_install:
  - sudo apt-get update
  - sudo apt-get install ffmpeg
script:
  - RAILS_ENV=test bundle exec rspec
addons:
  code_climate:
    repo_token: 43b1e78634f2c45a48d04acd57c03e406f9fa18156229b0793f06e41dc759216